#!/bin/csh
#
# Thermal ellipsoid representations
# GM1-pentasaccharide from a complex with the cholera toxin B-pentamer
# refined with anisotropic displacement parameters at 1.25A resolution 
#
rm -rf setup.angles setup.matrix temp.tmp
#
rods                   < sugarG.pdb | render | display -geometry 50%x50%+0+0   -title GM1-OS avs:- &
sleep 3
#
rastep                 < sugarG.pdb | render | display -geometry 50%x50%+350+0 -title "50% probability" avs:- &
sleep 3
#
rastep -fancy2 -prob 30< sugarG.pdb | render | display -geometry 50%x50%+700+0 -title "fancy2 30% probability" avs:- &
sleep 3
#
rastep -fancy3         < sugarG.pdb | render | display -geometry 50%x50%+0+350 -title "fancy3" avs:- &
sleep 3
#
rastep -Bcolor 10. 40. < sugarG.pdb | render | display -geometry 50%x50%+350+350 -title "colored by B value" avs:- &
sleep 3
#
echo ""
echo ""
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo ""
echo "You should now have 5 windows tiled on the upper left of your display, "
echo "illustrating different thermal ellipsoid options in the rastep program."
echo ""
echo "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
echo ""
