#!/bin/csh
# E A Merritt March 1993
# Illustration of composed figure using Raster3D
# (assumes ImageMagick installed, if not then don't pipe output from render)
#
setenv TMPFILE  `mktemp /tmp/ex2.XXXXXX` || exit 1
setenv TMPBALLS `mktemp /tmp/ex2.XXXXXX` || exit 1
setenv TMPSUGAR `mktemp /tmp/ex2.XXXXXX` || exit 1
#
# figure consists of E. coli enterotoxin (protein as spheres)
# binding to GM1 pentasaccharide (sugars represented as rods)
# protruding from cell membrane (plane)
# 
# Attach atom colouring to front of PDB file
#
cat chaincolours.pdb LT.pdb > $TMPFILE
#
# space-filling representation of protein atoms
#
balls -h < $TMPFILE > $TMPBALLS
#
# draw oligosaccharide as stick model
#
cat sugarcolours.pdb sugars.pdb > $TMPFILE
rods  -h < $TMPFILE > $TMPSUGAR
#
# combine protein description with sugar description and 
# add in description of plane surface lying below both.
# At the front goes a file containing the header records
# describing the view angle, image size, lighting, etc.
#
cat header2.r3d plane.r3d $TMPSUGAR $TMPBALLS > $TMPFILE
#
# Feed the composite description through the rendering progran
# and pipe the output to the ImageMagick display utility.
# If you have built the SGI libimage version instead, then use
#  render example1.rgb < $TMPFILE; ipaste example1.rgb
#
render < $TMPFILE | display avs:-
#
# Clean up before leaving
#
rm -f $TMPFILE $TMPSUGAR $TMPBALLS
